#packages
install.packages('ggplot2',dependencies = T)
install.packages('expm',dependencies = T)
install.packages('markovchain',dependencies = T)
install.packages('diagram',dependencies = T)
install.packages('pracma',dependencies = T)
library(expm)
library(markovchain)
library(diagram)
library(pracma)